# syntax=docker/dockerfile:1

FROM postgis/postgis

ENV POSTGRES_PASSWORD=postgres 
ENV POSTGRES_DB world

# docker run --name postgis_server -p 5432:5432 -v pgdata:/var/lib/postgresql/data --network postgis_network -d postgistri
